import { useForm } from 'react-hook-form'
import { Link } from 'react-router-dom'
import { useMutation } from '@tanstack/react-query'
import { registerPortalAccount } from '../../../services/customer-portal.service'
import type { PortalRegistration } from '../../customer-portal/types/customer-portal.types'

export default function AccessRequestPage() {
  const { register, handleSubmit, formState: { errors } } = useForm<PortalRegistration>(); const mutation = useMutation({ mutationFn: registerPortalAccount })
  if (mutation.isSuccess) return <main className="min-h-screen bg-slate-50 p-8"><section className="mx-auto mt-20 max-w-lg rounded-2xl bg-white p-8 text-center shadow-sm"><h1 className="text-2xl font-bold">Solicitud recibida</h1><p className="mt-3 text-slate-600">Comercial revisará tus datos antes de habilitar el acceso.</p><Link to="/tienda" className="mt-6 inline-block font-bold text-[#CE0203]">Volver a la tienda</Link></section></main>
  return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:py-14"><div className="mx-auto max-w-[640px]"><Link to="/tienda" className="text-sm font-medium text-[#CE0203]">← Volver a la tienda</Link><section className="mt-5 rounded-[20px] bg-white p-6 shadow-sm sm:p-10"><h1 className="text-2xl font-bold">Solicita tu acceso como cliente</h1><p className="mt-2 text-sm text-slate-600">Tu cuenta queda pendiente hasta la aprobación comercial.</p><form className="mt-8 space-y-4" onSubmit={handleSubmit((data) => mutation.mutate(data))} noValidate><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre de la empresa" error={errors.companyName?.message}><input {...register('companyName', { required: 'Este campo es obligatorio', minLength: { value: 2, message: 'Mínimo 2 caracteres' } })}/></Field><Field label="NIT" error={errors.documentId?.message}><input {...register('documentId', { minLength: { value: 3, message: 'Mínimo 3 caracteres' } })}/></Field><Field label="Nombre de contacto" error={errors.contactName?.message}><input {...register('contactName', { required: 'Este campo es obligatorio', minLength: { value: 2, message: 'Mínimo 2 caracteres' } })}/></Field><Field label="Correo corporativo" error={errors.email?.message}><input type="email" {...register('email', { required: 'Este campo es obligatorio', pattern: { value: /^\S+@\S+\.\S+$/, message: 'Ingresa un correo válido' } })}/></Field><Field label="Teléfono" error={errors.phone?.message}><input {...register('phone', { minLength: { value: 7, message: 'Mínimo 7 caracteres' } })}/></Field><Field label="Tipo de cliente" error={errors.type?.message}><select {...register('type', { required: 'Selecciona un tipo' })}><option value="">Selecciona una opción</option><option value="INSTALLER">Instalador</option><option value="FINAL_CUSTOMER">Cliente final</option></select></Field><Field label="Contraseña" error={errors.password?.message}><input type="password" autoComplete="new-password" {...register('password', { required: 'Este campo es obligatorio', minLength: { value: 12, message: 'Usa al menos 12 caracteres' } })}/></Field></div>{mutation.isError && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">No fue posible enviar la solicitud. Verifica los datos e intenta nuevamente.</p>}<button disabled={mutation.isPending} className="mt-2 w-full rounded-[10px] bg-[#CE0203] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{mutation.isPending ? 'Enviando…' : 'Enviar solicitud'}</button></form></section></div></main>
}
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-slate-800">{label}<span className="mt-1.5 block [&_input]:w-full [&_input]:rounded-[10px] [&_input]:border [&_input]:border-slate-300 [&_input]:px-3 [&_input]:py-2.5 [&_select]:w-full [&_select]:rounded-[10px] [&_select]:border [&_select]:border-slate-300 [&_select]:bg-white [&_select]:px-3 [&_select]:py-2.5">{children}</span>{error && <span role="alert" className="mt-1 block text-xs text-red-700">{error}</span>}</label> }
