import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { useCustomerPortalLogin } from '../../customer-portal/hooks/useCustomerPortal'

type LoginForm = { email: string; password: string }
export default function ClientLoginPage() {
  const { register, handleSubmit, formState: { errors } } = useForm<LoginForm>()
  const login = useCustomerPortalLogin(); const navigate = useNavigate(); const [params] = useSearchParams()
  useEffect(() => { if (login.isSuccess) navigate(params.get('returnTo') || '/clientes/productos', { replace: true }) }, [login.isSuccess, navigate, params])
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-4"><section className="w-full max-w-md rounded-[20px] border border-slate-200 bg-white px-6 py-10 shadow-lg"><Link to="/" className="text-sm font-medium text-[#CE0203]">← Volver a la tienda</Link><h1 className="mt-10 text-2xl font-bold">Inicia sesión</h1><p className="mt-2 text-sm text-slate-600">Accede a tus precios comerciales.</p><form className="mt-7 space-y-5" onSubmit={handleSubmit(({ email, password }) => login.mutate({ email, password }))} noValidate><label className="block text-sm font-medium">Correo electrónico<input type="email" autoComplete="email" className="mt-1.5 w-full rounded-[10px] border border-slate-300 px-3 py-2.5" {...register('email', { required: 'Ingresa tu correo', pattern: { value: /^\S+@\S+\.\S+$/, message: 'Ingresa un correo válido' } })}/>{errors.email && <span className="mt-1 block text-xs text-red-700" role="alert">{errors.email.message}</span>}</label><label className="block text-sm font-medium">Contraseña<input type="password" autoComplete="current-password" className="mt-1.5 w-full rounded-[10px] border border-slate-300 px-3 py-2.5" {...register('password', { required: 'Ingresa tu contraseña' })}/>{errors.password && <span className="mt-1 block text-xs text-red-700" role="alert">{errors.password.message}</span>}</label>{login.isError && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">No pudimos iniciar sesión. Verifica tus credenciales o espera la aprobación de tu cuenta.</p>}<button disabled={login.isPending} className="w-full rounded-[10px] bg-[#CE0203] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{login.isPending ? 'Ingresando…' : 'Ingresar'}</button></form><p className="mt-6 text-sm text-slate-600">¿Aún no tienes acceso? <Link to="/clientes/solicitar-acceso" className="font-bold text-[#CE0203]">Solicita tu acceso</Link>.</p></section></main>
}
