import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { approvePortalAccount, fetchPendingPortalAccounts, rejectPortalAccount } from '../../../services/customer-portal.service'

export default function PortalApprovalQueue() {
  const client = useQueryClient(); const [reason, setReason] = useState<Record<string, string>>({})
  const pending = useQuery({ queryKey: ['customer-portal', 'pending-accounts'], queryFn: fetchPendingPortalAccounts, retry: false })
  const invalidate = () => client.invalidateQueries({ queryKey: ['customer-portal', 'pending-accounts'] })
  const approve = useMutation({ mutationFn: (id: string) => approvePortalAccount(id), onSuccess: invalidate })
  const reject = useMutation({ mutationFn: ({ id, value }: { id: string; value: string }) => rejectPortalAccount(id, value), onSuccess: invalidate })
  return <section className="rounded-xl border border-neutral-200 bg-white p-4 shadow-sm"><div><h2 className="font-condensed text-lg font-semibold text-neutral-800">Solicitudes de acceso al portal</h2><p className="mt-1 text-sm text-neutral-500">Aprobar crea o vincula el cliente y habilita su tarifa configurada.</p></div>{pending.isLoading ? <p className="mt-4 text-sm text-neutral-500">Cargando solicitudes…</p> : pending.isError ? <p className="mt-4 text-sm text-[var(--color-error)]" role="alert">No se pudieron cargar las solicitudes.</p> : !pending.data?.length ? <p className="mt-4 text-sm text-neutral-500">No hay solicitudes pendientes.</p> : <div className="mt-4 space-y-3">{pending.data.map((account) => <article key={account.id} className="rounded-lg border border-neutral-200 p-3"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><p className="font-medium text-neutral-800">{account.companyName}</p><p className="text-sm text-neutral-600">{account.contactName} · {account.email}</p><p className="text-xs text-neutral-500">{account.type === 'INSTALLER' ? 'Instalador' : 'Cliente final'} · {account.documentId || 'Sin NIT'}</p></div><div className="flex gap-2"><button type="button" disabled={approve.isPending || reject.isPending} onClick={() => approve.mutate(account.id)} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">Aprobar</button><button type="button" disabled={!reason[account.id]?.trim() || approve.isPending || reject.isPending} onClick={() => reject.mutate({ id: account.id, value: reason[account.id] || '' })} className="rounded-lg border border-red-300 px-3 py-2 text-sm font-semibold text-red-700 disabled:opacity-50">Rechazar</button></div></div><label className="mt-3 block text-xs text-neutral-600">Motivo de rechazo (requerido para rechazar)<input value={reason[account.id] || ''} onChange={(event) => setReason((current) => ({ ...current, [account.id]: event.target.value }))} className="mt-1 w-full rounded border border-neutral-300 px-2 py-1.5 text-sm" /></label></article>)}</div>}</section>
}
